VPATH = $(PWD)/cint:$(PWD)/src:$(PWD)/lib:$(PWD)/rbgui

### Include the user-defined portion of the makefile
include $(PWD)/user/Makefile.user

### Variable definitions
SRC=$(PWD)/src
CINT=$(PWD)/cint
USER=$(PWD)/user
ROOTGLIBS = $(shell root-config --glibs) -lXMLParser -lThread -lTreePlayer
RPATH    += -Wl,-rpath,$(ROOTSYS)/lib -Wl,-rpath,$(PWD)/lib
DYLIB=-shared -fPIC
INCFLAGS=-I$(SRC) -I$(CINT) -I$(USER) $(USER_INCLUDES)
CXXFLAGS=$(INCFLAGS) -L$(ROOTSYS)/lib -L$(PWD)/lib $(STOCK_BUFFERS) -DBUFFER_TYPE=$(USER_BUFFER_TYPE) \
-D_MIDAS_ONLINE_ -L$(MIDAS_ONLINE)/linux/lib -I$(MIDAS_ONLINE)/include


ifdef ROOTSYS
ROOTGLIBS = -L$(ROOTSYS)/lib $(shell $(ROOTSYS)/bin/root-config --glibs) -lXMLParser -lThread -lTreePlayer
CXXFLAGS += -DHAVE_ROOT $(shell $(ROOTSYS)/bin/root-config --cflags) -I$(ROOTSYS)/include
endif

# optional MIDAS libraries
ifdef MIDASSYS
MIDASLIBS = $(MIDASSYS)/linux/lib/libmidas.a -lutil -lrt
CXXFLAGS += -DHAVE_MIDAS -DOS_LINUX -Dextname -I$(MIDASSYS)/include
MIDASONLINE=$(SRC)/midas/TMidasOnline.cxx

UNAME=$(shell uname)
ifeq ($(UNAME),Darwin)
CXXFLAGS += -DOS_LINUX -DOS_DARWIN
MIDASLIBS = $(MIDASSYS)/darwin/lib/libmidas.a
DYLIB=-dynamiclib -single_module -undefined dynamic_lookup 
RPATH=
endif

endif



#### MAIN PROGRAM ####
all: rootbeer

rootbeer: libRBHist.so libRootbeer.so $(SRC)/main.cc 
	g++ $(CXXFLAGS) $(INCFLAGS) -lRootbeer $(SRC)/main.cc -o rootbeer $(MIDASLIBS) $(ROOTGLIBS) -lm -lz -lpthread $(RPATH) -I$(ROOTSYS)/include ; echo ""


#### ROOTBEER LIBRARY ####
SOURCES= $(USER_SOURCES) $(MIDASONLINE) $(SRC)/Data.cxx $(SRC)/Rootbeer.cxx $(PWD)/user/Skeleton.cxx $(SRC)/Attach.cxx $(SRC)/Canvas.cxx $(SRC)/WriteConfig.cxx \
$(SRC)/midas/TMidasEvent.cxx $(SRC)/midas/rbMidasEvent.cxx

HEADERS=$(SRC)/Rootbeer.hxx $(SRC)/Data.hxx $(SRC)/midas/rbMidasEvent.h $(USER_HEADERS)

libRootbeer.so: libRBHist.so cint/RBDictionary.cxx $(SOURCES)
	g++ $(DYLIB) -o $(PWD)/lib/$@ -lRBHist $(CXXFLAGS) $(MIDASLIBS) $(ROOTGLIBS) $(RPATH)  -p cint/RBDictionary.cxx $(SOURCES)  ; echo ""


cint/RBDictionary.cxx: $(HEADERS) Linkdef.h
	rootcint -f $@ -c $(CXXFLAGS)  -p $^ ; echo ""



#### COMPILE HISTOGRAM LIBRARY ####

libRBHist.so: Hist.cxx cint/HistDictionary.cxx
	g++ $(DYLIB) -o $(PWD)/lib/$@ $(CXXFLAGS) -lTreePlayer  -p $^   $(ROOTGLIBS) $(RPATH) ; echo ""


cint/HistDictionary.cxx: Hist.hxx LockingPointer.hxx HistLinkdef.h
	rootcint -f $@ -c $(CXXFLAGS) -p $^ ; echo ""



#### REMOVE EVERYTHING GENERATED BY MAKE ####

clean:
	rm -f lib/*.so rootbeer cint/RBDictionary.* cint/HistDictionary.* rbgui/HistDict.*



#### FOR DOXYGEN ####

doc:
	cd $(PWD)/doxygen ; doxygen Doxyfile ; cd latex; make; cd $(PWD)

doccopy:
	cd $(PWD)/doxygen ; doxygen Doxyfile ; cd latex; make; cd $(PWD) ; \
	$(PWD)/doxygen/copydoc.sh




#### GUI STUFF ####


GUI=$(PWD)/rbgui
GUIHEADERS=$(GUI)/HistViewer.h $(GUI)/HistMaker.h $(GUI)/TH2D_SF.h $(GUI)/TH1D_SF.h $(GUI)/TH3D_SF.h
GUISOURCES=$(GUI)/HistViewer.cc $(GUI)/HistMaker.cc $(GUI)/TH2D_SF.cc $(GUI)/TH1D_SF.cc $(GUI)/TH3D_SF.cc

GUIROOTFLAGS=-dynamiclib -single_module -undefined dynamic_lookup `root-config --cflags --libs` -lTreePlayer

GUICXXFLAGS=-fPIC

gui: librbgui.so

librbgui.so: libRBHist.so HistDict.cxx $(GUISOURCES)
	g++ -L$(PWD)/lib -lRBHist -shared -o $(PWD)/lib/$@ $(GUICXXFLAGS) -I/opt/local/include/root $(GUI)/HistDict.cxx $(GUISOURCES) $(GUIROOTFLAGS) -I$(PWD)/src

HistDict.cxx: $(GUIHEADERS) rbgui/Linkdef.h
	rootcint -f rbgui/$@ -c -Isrc $(GUICXXFLAGS) -p $^

#HistViewer.o:
#	g++ -c $(ROOTFLAGS) $(CXXFLAGS) HistViewer.cc

guiclean:
	rm -f lib/librbgui.so rbgui/HistDict.*
