/********************************************************************
* rbgui/HistDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error rbgui/HistDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableHistDict();
extern void G__cpp_setup_inheritanceHistDict();
extern void G__cpp_setup_typetableHistDict();
extern void G__cpp_setup_memvarHistDict();
extern void G__cpp_setup_globalHistDict();
extern void G__cpp_setup_memfuncHistDict();
extern void G__cpp_setup_funcHistDict();
extern void G__set_cpp_environmentHistDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/Users/gchristian/soft/develop/rootbeer/rbgui/HistViewer.h"
#include "/Users/gchristian/soft/develop/rootbeer/rbgui/HistMaker.h"
#include "/Users/gchristian/soft/develop/rootbeer/rbgui/TH2D_SF.h"
#include "/Users/gchristian/soft/develop/rootbeer/rbgui/TH1D_SF.h"
#include "/Users/gchristian/soft/develop/rootbeer/rbgui/TH3D_SF.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__HistDictLN_TObject;
extern G__linked_taginfo G__HistDictLN_TString;
extern G__linked_taginfo G__HistDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__HistDictLN_string;
extern G__linked_taginfo G__HistDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__HistDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__HistDictLN_TList;
extern G__linked_taginfo G__HistDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__HistDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__HistDictLN_TQObject;
extern G__linked_taginfo G__HistDictLN_TQObjSender;
extern G__linked_taginfo G__HistDictLN_TGObject;
extern G__linked_taginfo G__HistDictLN_TGWindow;
extern G__linked_taginfo G__HistDictLN_TGFrame;
extern G__linked_taginfo G__HistDictLN_TGLayoutHints;
extern G__linked_taginfo G__HistDictLN_TGString;
extern G__linked_taginfo G__HistDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__HistDictLN_TGTextButton;
extern G__linked_taginfo G__HistDictLN_TGHorizontalFrame;
extern G__linked_taginfo G__HistDictLN_TGMainFrame;
extern G__linked_taginfo G__HistDictLN_TGGroupFrame;
extern G__linked_taginfo G__HistDictLN_TTree;
extern G__linked_taginfo G__HistDictLN_TFile;
extern G__linked_taginfo G__HistDictLN_TBranchObject;
extern G__linked_taginfo G__HistDictLN_TGPopupMenu;
extern G__linked_taginfo G__HistDictLN_TGMenuBar;
extern G__linked_taginfo G__HistDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__HistDictLN_TGTab;
extern G__linked_taginfo G__HistDictLN_TGListView;
extern G__linked_taginfo G__HistDictLN_TGTextEntry;
extern G__linked_taginfo G__HistDictLN_TBranchElement;
extern G__linked_taginfo G__HistDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__HistDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__HistDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__HistDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__HistDictLN_TH1D;
extern G__linked_taginfo G__HistDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__HistDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__HistDictLN_TH2D;
extern G__linked_taginfo G__HistDictLN_TH3D;
extern G__linked_taginfo G__HistDictLN_HistMaker;
extern G__linked_taginfo G__HistDictLN_HistViewer;
extern G__linked_taginfo G__HistDictLN_vectorlETGCompositeFramemUcOallocatorlETGCompositeFramemUgRsPgR;
extern G__linked_taginfo G__HistDictLN_reverse_iteratorlEvectorlETGCompositeFramemUcOallocatorlETGCompositeFramemUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__HistDictLN_vectorlETRootEmbeddedCanvasmUcOallocatorlETRootEmbeddedCanvasmUgRsPgR;
extern G__linked_taginfo G__HistDictLN_reverse_iteratorlEvectorlETRootEmbeddedCanvasmUcOallocatorlETRootEmbeddedCanvasmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__HistDictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__HistDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__HistDictLN_TGLVContainer;
extern G__linked_taginfo G__HistDictLN_TGLVEntry;
extern G__linked_taginfo G__HistDictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__HistDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__HistDictLN_rb;
extern G__linked_taginfo G__HistDictLN_rbcLcLHist;
extern G__linked_taginfo G__HistDictLN_vectorlETTreeFormulamUcOallocatorlETTreeFormulamUgRsPgR;
extern G__linked_taginfo G__HistDictLN_reverse_iteratorlEvectorlETTreeFormulamUcOallocatorlETTreeFormulamUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__HistDictLN_TH1D_SF;
extern G__linked_taginfo G__HistDictLN_maplEstringcOTH1D_SFmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTH1D_SFmUgRsPgRsPgR;
extern G__linked_taginfo G__HistDictLN_TH2D_SF;
extern G__linked_taginfo G__HistDictLN_maplEstringcOTH2D_SFmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTH2D_SFmUgRsPgRsPgR;
extern G__linked_taginfo G__HistDictLN_TH3D_SF;
extern G__linked_taginfo G__HistDictLN_maplEstringcOTH3D_SFmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTH3D_SFmUgRsPgRsPgR;
extern G__linked_taginfo G__HistDictLN_CommandIdentifiers;
extern G__linked_taginfo G__HistDictLN_TGLVEntry_mod;
extern G__linked_taginfo G__HistDictLN_maplEintcOstringcOlesslEintgRcOallocatorlEpairlEconstsPintcOstringgRsPgRsPgR;

/* STUB derived class for protected member access */
